name: 'Setup Android NDK'
description: 'Setup an Android NDK environment by downloading and returning it via ndk-path'
author: 'Raphaël Thériault'
inputs:
  ndk-version:
    required: true
    description: 'Exact version to use'
outputs:
  ndk-path:
    description: 'Installation path'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'green'
